# WhatATheme
markdown: kramdown

# URL of the Site
url: https://taliahelle.github.io
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Talia Armato-Helle
# Description of the Site
description: Marketing Leader
# URL of Image of the Site
site-image: /assets/images/lake.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: /assets/images/favicon.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/mtn_1.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: talia.helle@gmail.com
facebook_username: 
twitter_username:
instagram_username: 
linkedin_username: https://www.linkedin.com/in/talia-armato-helle/
github_username: https://www.github.com/italianhelle
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: 

# Name of the Author
author-name: Talia Armato-helle
# URL for the Image of the Author
author-image: /assets/images/talia.jpg
# 60 Words About the Author
author-about: Marketing leader in gaming.
author-url: https://github.com/italiahelle

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
